version: "3.8"
services:
  flask:
    build: ./app
    command: gunicorn -b 0.0.0.0:5000 app:app --reload
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=TRUE
    ports:
      - 5001:5000
    volumes:
      - ./app:/app


